{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "63852d6a-f520-4c50-a795-707422f2a5e9",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "select * from retail_sales_dataset\n",
    "limit 100;\n",
    "\n",
    "select distinct `Product Category`\n",
    "from retail_sales_dataset;\n",
    "\n",
    "select distinct gender\n",
    "from retail_sales_dataset;\n",
    "\n",
    "select count('TransactionID')\n",
    "from retail_sales_dataset;\n",
    "\n",
    "select *\n",
    "from retail_sales_dataset\n",
    "where Age>30;\n",
    "\n",
    "select *\n",
    "from retail_sales_dataset\n",
    "where Age between 30 and 50;\n",
    "\n",
    "select *\n",
    "from retail_sales_dataset\n",
    "order by Quantity Desc\n",
    "limit 100;\n",
    "\n",
    "select *\n",
    "from retail_sales_dataset\n",
    "order by `Price per Unit` Desc\n",
    "limit 100;\n",
    "\n",
    "select Gender,\n",
    "       COUNT(`Transaction ID`) AS Customers\n",
    "from retail_sales_dataset\n",
    "Group by Gender;\n",
    "\n",
    "select Gender,\n",
    "       COUNT(`Customer ID`) AS Customers\n",
    "from retail_sales_dataset\n",
    "where Age>30\n",
    "Group by Gender;\n",
    "\n",
    "select Gender,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by Gender;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`\n",
    "       Order by Total Desc;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`\n",
    "       Having Total >150000\n",
    "       Order by Total Desc;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`\n",
    "       Having Total >150000\n",
    "       Order by Total Asc;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`\n",
    "       Having Total Between 100000 AND 150000\n",
    "       Order by Total Desc;\n",
    "\n",
    "select `Product Category`,\n",
    "       SUM(`Total Amount`) AS Total\n",
    "       from retail_sales_dataset\n",
    "       Group by `Product Category`\n",
    "       Having Total Not Between 100000 AND 150000\n",
    "       Order by Total Desc;\n",
    "\n",
    "-- 02/06/2026 \n",
    "-- Display only the Customer ID and Product Category columns \n",
    "SELECT `Customer ID`,\n",
    "        `Product Category`\n",
    "FROM retail_sales_dataset;\n",
    "\n",
    "--Display all electronics sales transactions\n",
    "SELECT *\n",
    "FROM retail_sales_dataset\n",
    "WHERE `Product Category`='Electronics';\n",
    "\n",
    "--Display customers older than 40\n",
    "SELECT *\n",
    "FROM retail_sales_dataset\n",
    "WHERE Age >40;\n",
    "\n",
    "--Display transactions where the quantity purchased is 3 or more\n",
    "SELECT *\n",
    "FROM retail_sales_dataset\n",
    "WHERE Quantity >=3;\n",
    "\n",
    "--Display beauty product sales where the total amount is greater than 100\n",
    "SELECT *\n",
    "FROM retail_sales_dataset\n",
    "WHERE `Product Category` = 'Beauty' \n",
    "AND `Total Amount`>100;\n",
    "\n",
    "-- Display customers whose ages are between 25 and 35\n",
    "SELECT *\n",
    "FROM retail_sales_dataset\n",
    "WHERE Age BETWEEN 25 AND 35;\n",
    "\n",
    "--Calculate the total sales amount for all transactions\n",
    "SELECT SUM(`Total Amount`) AS Total_sales\n",
    "FROM retail_sales_dataset;\n",
    "\n",
    "--03/06/26\n",
    "--connecting Databricks to Github\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "brightlearn",
     "schema": "data"
    }
   },
   "notebookName": "(Clone) CLASS PRACTISE.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
